### ISSUE TITLE
Page information

### ISSUE THREAD

**Issue by Indribell** [nebrelbug/squirrelly.js.org#4]
Some suggestion regarding the documentation. Squirrelly has if/else/each/foreach build in functionality but it is very well hidden under "Built-in Helpers".

* It is advised to split this and add each item as sub menu under The Basics. Allowing for the viewing as: 
```
Basics
-- If/Else
-- Each
-- Foreach
Global References
```

* It may also be advice to have as first page in your gitbook a overview of some basic functionality. See for example some competing alternatives:
https://mozilla.github.io/nunjucks/
https://pugjs.org/api/getting-started.html
Showing examples, benchmark result etc as "overview". Currently it opens on the Readme.

* The Change log page is out of date with version 0.5 instead of 0.7.

* The Performance page shows a link to the benchmarks but no benchmarks. This requires opening up another page.

* Another piece of information that can be useful, is pointing out that squirrelly makes heavy use off ES6 Template Literals? So it shows up in Google search results.

I hope these points are useful.

**Comment by bgub** [comment]
Thank you for the suggestions! I'll update the overview page, the changelog, and the benchmarks page. Squirrelly actually doesn't use template literals so it can work with ES5: maybe I should highlight that as a benefit.
